version: "3"
services:
  app:
    container_name: thai-mobility-api
    restart: always
    image: hdminh247/thai-mobility-api:latest
    ports:
      - "5502:5502"
    command: ./wait-for.sh mongo:27017 -- node server.js
    links:
      - mongo
    depends_on:
      - mongoClient
  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  mongoClient:
    container_name: my-mongo-client
    image: hdminh247/mongo-client
    command: ./add-user.sh
    links:
      - mongo
    depends_on:
      - mongo
  web:
    container_name: thai-mobility-web
    image: hdminh247/thai-mobility-web:latest
    ports:
    - "8081:80"
  cms:
    container_name: thai-mobility-cms
    image: hdminh247/thai-mobility-cms:latest
    ports:
    - "8082:80"